### ISSUE TITLE
el.scrollTo not working in IE

### ISSUE THREAD

**Issue by navinsaini** [akariv/hatool#12]
https://github.com/akariv/hatool/blob/master/projects/hatool/src/lib/messages/messages.component.ts#L26

Please provide support for Internet Exporer

**Comment by akariv** [comment]
A common solution, if IE support is crucial, would be to use a polyfill in
your app - for example this one:
https://www.npmjs.com/package/smoothscroll-polyfill

**Comment by navinsaini** [comment]
Thanks, That worked :)
